name: CI

on: [push, pull_request]

jobs:
  build-php:
    name: Build PHP
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        typo3: ['^10', '11.*@dev']
        php: ['7.2', '7.3', '7.4']
    steps:
    - name: Start Database-Server
      run: |
        sudo /etc/init.d/mysql start
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up PHP Version
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php }}
    - name: Install
      run: |
        composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
        git checkout composer.json
    - name: Lint
      run: |
        composer test:php:lint
    - name: CGL
      run: |
        composer test:php:cgl
    - name: Unit Tests
      run: |
        composer test:php:unit
    - name: Functional Tests
      run: |
        composer test:php:functional
      env:
        COMPOSER_PROCESS_TIMEOUT: 1200
        typo3DatabaseHost: 127.0.0.1
        typo3DatabaseName: t3func
        typo3DatabasePassword: root
        typo3DatabaseUsername: root
